Update template.yaml

diff --git a/.github/workflows/template.yaml b/.github/workflows/template.yaml
--- a/.github/workflows/template.yaml
+++ b/.github/workflows/template.yaml
@@ -17,7 +17,7 @@ jobs:
     env:
       TF_WORKING_DIR: ${{ github.workspace }}/${{ github.event.inputs.resourcetype }}  # Correct working directory
       TF_VERSION: '1.3.5'  # Specify the Terraform version
-      BUILD_NUMBER: ${{ github.run_id }}  # Unique build number using GitHub run ID
+      BUILD_NUMBER: ${{ github.run_id }}  # Get the GitHub run ID as the build number
 
     steps:
     # Step 1: Checkout the repository
@@ -48,16 +48,17 @@ jobs:
       run: |
         echo "Running Checkov for security analysis on Terraform configuration..."
         pip install checkov  # Install Checkov
-        checkov -d ${{ env.TF_WORKING_DIR }} -o json -o checkov_output_${{ env.BUILD_NUMBER }}.json || echo "Checkov failed, but output will be saved."  # Run Checkov and capture failure without stopping
+        # Run Checkov and save output even if it fails
+        checkov -d ${{ env.TF_WORKING_DIR }} -o json -o checkov_outputs/checkov_output_${{ env.BUILD_NUMBER }}.json || echo "Checkov failed, but output will be saved."
 
     # Step 6: Copy Checkov output to the repository even if Checkov fails
     - name: Copy Checkov output to the repository
       run: |
         echo "Copying Checkov output file to the repository..."
-
+        
         # Dynamically set the file name based on the build number
-        CHECKOV_OUTPUT_FILE="checkov_output_${{ env.BUILD_NUMBER }}.json"
-
+        CHECKOV_OUTPUT_FILE="checkov_outputs/checkov_output_${{ env.BUILD_NUMBER }}.json"
+        
         # Ensure the Checkov output file exists before adding it to Git
         if [ -f "$CHECKOV_OUTPUT_FILE" ]; then
           # Create the checkov_outputs directory if it doesn't exist
@@ -77,7 +78,7 @@ jobs:
           git config --global user.name "sivalakshmimettu"
           
           # Push the changes back to the repository using the default GITHUB_TOKEN
-          git push https://github.com/${{ github.repository }} HEAD:${{ github.ref }}
+          git push https://github.com/sivalakshmimettu/webapptest HEAD:refs/heads/main
         else
           echo "Checkov output file does not exist!"
           exit 1
